title: Alejo's space
author: Alejandro Castilleja
email: zed.dac@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little space that I use to unleash my creativity and test some things.
theme: minima
# social links
twitter_username: ZedAon
github_username:  D-Alejo

show_excerpts: true # set to false to remove excerpts on the homepage
